# Publish Release Workflow
name: Publish Release

on:
  release:
    types: [published]

env:
  # MINECRAFT_VERSION will be set dynamically from gradle.properties
  JAVA_VERSION: 21

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set Minecraft Version from gradle.properties
        id: get_minecraft_version
        run: |
          version=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)
          echo "MINECRAFT_VERSION=${version}" >> $GITHUB_ENV
          echo "Detected Minecraft version: ${version}"

      - name: Publish to CurseForge & Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ secrets.CURSEFORGE_PROJECT_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          version: ${{ github.event.release.tag_name }}
          version-type: release
          changelog-file: CHANGELOG.md
          
          loaders: fabric
          game-versions: ${{ env.MINECRAFT_VERSION }}
          java: ${{ env.JAVA_VERSION }}

      - name: Publish Complete Notification
        run: echo "Publish to CurseForge and Modrinth completed successfully!" 
