name: PR Build and Release

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run Gradle Build
        run: ./gradlew build

      # PR タイトルに [release] が含まれる場合に成果物をアップロード（プレビュー用）
      - name: Upload Build Artifact (PR preview)
        if: contains(github.event.pull_request.title, '[release]')
        uses: actions/upload-artifact@v3
        with:
          name: pr-build-artifact
          path: build/libs/*.jar

  release:
    name: Release via Gradle Release Plugin
    needs: build
    if: contains(github.event.pull_request.title, '[release]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java 21 (Temurin) for Release
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git for Automated Release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Gradle Release
        # gradle-release プラグインへ対して自動実行オプションを付与
        run: ./gradlew release -Prelease.useAutomaticVersion=true --no-daemon

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: build/libs/*.jar 