# Automatically build the project and create a GitHub release with the built artifacts
# when a new tag is pushed. This workflow is triggered by pushing a tag that starts with 'v'.

name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: set version without SNAPSHOT
        run: |
          # Remove v prefix from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update mod_version in gradle.properties
          sed -i "s/mod_version=.*-SNAPSHOT/mod_version=$VERSION/g" gradle.properties
      - name: build
        run: ./gradlew build
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/libs/*.jar 